miknassa/users/routes.py
from flask import Blueprint
from flask import render_template, flash, redirect, url_for, request
from flask_login import login_user, current_user, logout_user, login_required
from miknassa.users.forms import (
    JoinForm,
    LoginForm,
    EditProfileForm,
    ChangePasswordForm,
    ForgotPasswordForm,
    ResetPasswordForm,
)
from miknassa.models import User, Municipality, Dayra, Wilaya
from miknassa.users.helper import sendResetEmail
from miknassa.helper import renameImage
from miknassa import db, bcrypt


usersBp = Blueprint("users", __name__)


@usersBp.route("/miknassa", methods=["GET", "POST"])
def login():
    isHomepage = False
    isLoginpage = True

    try:
        if current_user.is_authenticated:
            return redirect(url_for("main.home"))

        joinForm = JoinForm()
        loginForm = LoginForm()

        if request.form.get("submit") == "انضمام":
            if joinForm.validate_on_submit():
                hashedPassword = bcrypt.generate_password_hash(
                    joinForm.password.data
                ).decode("utf-8")
                user = User(
                    firstName=joinForm.firstName.data,
                    lastName=joinForm.lastName.data,
                    username=joinForm.username.data,
                    gender=joinForm.gender.data,
                    email=joinForm.email.data,
                    phoneNumber=joinForm.phoneNumber.data,
                    municipalityId=joinForm.municipality.data,
                    userTypeId=1,
                    password=hashedPassword,
                )
                db.session.add(user)
                db.session.commit()
                flash(
                    f"مرحبا بك {joinForm.username.data}، تم انشاء الحساب بنجاح.",
                    "success",
                )
                return redirect(url_for("users.login"))
            else:
                flash("تأكّد من صحة الإدخال.", "warning")
    except Exception as e:
        db.session.rollback()
        # raise
        flash("يوجد مشكلة فالإتّصال\nحاول مجدّدا في وقت لاحق", 500, "error")

    finally:
        db.session.close()

    try:
        if request.form.get("submit") == "دخـول":
            if loginForm.validate_on_submit():
                user = User.query.filter_by(email=loginForm.email.data).first()

                if user and bcrypt.check_password_hash(
                    user.password, loginForm.password.data
                ):
                    login_user(user, remember=loginForm.remember.data)
                    nextPage = request.args.get("next")
                    flash(f"مرحبا {user.username} تم تسجيل الدخول بنجاح.", "success")
                    if user.userTypeId == 1:
                        return (
                            redirect(nextPage)
                            if nextPage
                            else redirect(url_for("main.home"))
                        )
                    elif user.userTypeId == 2:
                        return (
                            redirect(nextPage)
                            if nextPage
                            else redirect(url_for("application.dashboard"))
                        )
                    elif user.userTypeId == 3:
                        return (
                            redirect(nextPage)
                            if nextPage
                            else redirect(url_for("application.dashboard"))
                        )
                    else:
                        flash("يوجد خلل في الحساب", "error")
                else:
                    flash("فشل تسجيل الدخول، حاول مجدّدًا.", "error")
    except Exception as e:
        # raise
        flash("يوجد مشكلة فالإتّصال\nحاول مجدّدا في وقت لاحق", 500, "error")

    finally:
        db.session.close()

    return render_template(
        "forms/login.html",
        joinForm=joinForm,
        loginForm=loginForm,
        isHomepage=isHomepage,
        isLoginpage = isLoginpage,
    )


@usersBp.route("/logout")
@login_required
def logout():
    logout_user()
    flash("تم تسجيل الخروج بنجاح", "success")
    return redirect(url_for("users.login"))


@usersBp.route("/reset password", methods=["GET", "POST"])
def forgotPassword():
    isHomepage = False

    try:
        if current_user.is_authenticated:
            return redirect(url_for("main.home"))
        forgotPasswordForm = ForgotPasswordForm()
        if forgotPasswordForm.validate_on_submit():
            user = User.query.filter_by(email=forgotPasswordForm.email.data).first()
            if user:
                sendResetEmail(user)
            flash(
                "إذا كان هذا الحساب موجود فعلا فستستقبل بريدا إلكترونيًّا لاستعادة كلمة المرور.",
                "info",
            )
            return redirect(url_for("users.login"))
    except Exception as e:
        db.session.close()
        # raise
        flash("يوجد مشكلة فالإتّصال\nحاول مجدّدا في وقت لاحق", 500, "error")

    return render_template(
        "forms/forgotPassword.html",
        title="Reset Password",
        forgotPasswordForm=forgotPasswordForm,
        isHomepage=isHomepage,
    )


@usersBp.route("/reset password/<token>", methods=["GET", "POST"])
def resetPassword(token):
    resetPasswordForm = ResetPasswordForm()
    isHomepage = False

    try:
        if current_user.is_authenticated:
            return redirect(url_for("main.home"))

        user = User.verifyResetToken(token)

        if not user:
            flash("الرمز الخاص غير متاح أو منتهي الصلاحية.", "warning")
            return redirect(url_for("users.forgotPassword"))

        if resetPasswordForm.validate_on_submit():
            hashedPassword = bcrypt.generate_password_hash(
                resetPasswordForm.password.data
            ).decode("utf-8")
            user.password = hashedPassword
            db.session.commit()
            flash("تم تحديث كلمة مرورك بنجاح، تستطيع الآن تسجيل الدخول.", "success")
            return redirect(url_for("users.login"))

    except Exception as e:
        db.session.rollback()
        db.session.close()
        # raise
        flash("يوجد مشكلة فالإتّصال\nحاول مجدّدا في وقت لاحق", 500, "error")

    return render_template(
        "forms/resetPassword.html",
        title="Reset Password",
        resetPasswordForm=resetPasswordForm,
        isHomepage=isHomepage,
    )


@usersBp.route("/profile")
@login_required
def profile():
    isHomepage = False
    isProfilepage = True

    try:
        userData = User.query.filter_by(id=current_user.id).first()
        municipality = Municipality.query.filter_by(id=userData.municipalityId).first()
        dayra = Dayra.query.filter_by(id=municipality.dayraId).first()
        wilaya = Wilaya.query.filter_by(id=dayra.wilayaId).first()
        address = {
            "wilaya": wilaya.name,
            "dayra": dayra.name,
            "municipality": municipality.name,
        }
        image = url_for("static", filename=f"media/{userData.imageFile}")
        return render_template(
            "pages/profile.html",
            userData=userData,
            address=address,
            image=image,
            isHomepage=isHomepage,
            isProfilepage=isProfilepage,
        )
    except Exception as e:
        # raise
        flash("يوجد مشكلة فالإتّصال\nحاول مجدّدا في وقت لاحق", 500, "error")
        return redirect(url_for("users.login"))

    finally:
        db.session.close()


@usersBp.route("/edit profile", methods=["GET", "POST"])
@login_required
def editProfile():
    isHomepage = False
    username = current_user.username

    try:
        user = User.query.filter_by(id=current_user.id).first()
        municipality = Municipality.query.filter_by(id=user.municipalityId).first()
        dayra = Dayra.query.filter_by(id=municipality.dayraId).first()
        wilaya = Wilaya.query.filter_by(id=dayra.wilayaId).first()
        address = {
            "wilaya": wilaya.name,
            "dayra": dayra.name,
            "municipality": municipality.name,
        }
        editProfileForm = EditProfileForm()
        image = url_for("static", filename=f"media/{current_user.imageFile}")

        if editProfileForm.validate_on_submit():
            if editProfileForm.imageFile.data:
                image = renameImage(editProfileForm.imageFile.data)
                user.imageFile = image

            user.firstName = (
                editProfileForm.firstName.data
                if editProfileForm.firstName.data
                else user.firstName
            )
            user.lastName = (
                editProfileForm.lastName.data
                if editProfileForm.lastName.data
                else user.lastName
            )
            user.username = (
                editProfileForm.username.data
                if editProfileForm.username.data
                else user.username
            )
            user.gender = (
                editProfileForm.gender.data
                if editProfileForm.gender.data
                else user.gender
            )
            user.email = (
                editProfileForm.email.data if editProfileForm.email.data else user.email
            )
            user.phoneNumber = (
                editProfileForm.phoneNumber.data
                if editProfileForm.phoneNumber.data
                else user.phoneNumber
            )
            user.municipalityId = (
                editProfileForm.municipality.data
                if editProfileForm.municipality.data
                else user.municipality
            )
            user.houseNumber = editProfileForm.houseNumber.data
            user.location = editProfileForm.location.data
            user.birthDate = (
                editProfileForm.birthDate.data
                if editProfileForm.birthDate.data
                else user.birthDate
            )
            user.birthPlace = editProfileForm.birthPlace.data

            db.session.commit()

miknassa/templates/pages/dashboard.html
{% extends "layout.html" %}

{% block stylesheets %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/dashboard.css' ) }}">
{% endblock stylesheets %}

{% block body %}
{% include 'parts/nav.html' %}
{% include 'additions/flashMessages.html' %}
<div class="dashboard">
    <h1 class="title">لوحة التحكم</h1>
    <div class="formBtns">
        <p class="formBtn joinBtn" onclick="toggleForm('operation')">المهـام</p>
        {% if current_user.userTypeId == 3 %}
        <p class="formBtn enterBtn" onclick="toggleForm('roleChanging')">الأدور</p>
        <p class="formBtn joinBtn" onclick="toggleForm('truckAdding')">إدراج شاحنة</p>
        {% endif %}
    </div>
    <div class="formBox">
        {% include 'pages/operation.html' %}

        {% if current_user.userTypeId == 3 %}
        {% include 'pages/roleChanging.html' %}
        {% include 'pages/truckAdding.html' %}
        {% endif %}
    </div>
</div>
</div>

<script src="{{ url_for('static', filename='js/dashboard.js' ) }}"></script>
{% endblock body %}

miknassa/templates/pages/googleMap.html
{% extends 'layoutWithBootstrap.html' %}
{% block body %}
{% include 'additions/flashMessages.html' %}

<h1>التطبيق..</h1>
<div style="text-align: center !important; direction: ltr !important;">
    <div id="map" style="height: 70vh; width: 100%; text-align: center !important;"></div>
</div>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAa5wziHjN2Dq5vVzxNStJyMbMkhSCXWSI"></script>
<script src="{{ url_for('static', filename='js/app.js' ) }}"></script>
{% endblock body %}

miknassa/templates/pages/home.html
{% extends "layout.html" %}

{% block body %}
{% include 'parts/header.html'   %}
<script src="{{ url_for('static', filename='js/backgroundScript.js') }}"></script>

<main>
    <section id="1">
        <h2>مشروع مكنسة</h2>
        <div class="about">
            <img src="{{ url_for('static', filename='images/1.png') }}" alt="">
            <div>
                <p>الشركة نفسها هي شركة ناجحة جدا. ولكننا لا نقود المستمتعين أبدًا بقسوة أكثر مما قيل له، وحتى لا يعلموا أنه سيتبعه آلام، لأنك ترى في التدريب الذي برفضه المباركين قد حلوا بمشكلة عظيمة. سبب! ما هو نوع الرفض الذي يعيقه؟ سأأتي لمن، ولكن متعة عدم الاختيار هنا، فأنت ترى من هذه الأشياء حيث يجب اتباع بعض الواجبات، فهو يبحث عن ملذات ولدت لنا طرقًا لطيفة للرفض، لأنه يهرب من الألم لأنه! وأن يُطرد، وفيه متاعب وآلام، لا أحد يعلم هل فيهم لين، ومن يخفف عنهم الآلام، أليس كذلك؟ لقد أعمتهم عواقب اتباع الأوقات العصيبة، ويجب العفو عنهم، وهذه وسائل الراحة والملذات اختيارية؛ في الواقع، لا شيء يقع في هذه الحياة يمنع اللطيف من النفعي. سأشرح آلام وآلام هذا الاختيار بالإطراء. أكرم من يريد ألا يحدث لنا كل المشاكل والملذات! إنهم لا يختارون أبدًا، لكنهم يوفرون فرصة عظيمة. لنا، فليكن تمييزًا، حتى بالنسبة للبعض الذين في هذا الوقت نفسه، من لا شيء سوى الملذات، فهذه هي المشاكل التي تنفع فيها الآلام!</p>
            </div>
        </div>
    </section>

    <section id="2">
        <div class="team">
            <h2>فريق المشروع</h2>
            <div class="content">
                <div class="card">
                    <img loading="lazy" src="{{ url_for('static', filename='images/2.png') }}" alt="team member image">
                    <div class="data">
                        <h3>محمد</h3>
                        <p>باحث</p>
                    </div>
                </div>
                <div class="card">
                    <img loading="lazy" src="{{ url_for('static', filename='images/2.png') }}" alt="team member image">
                    <div class="data">
                        <h3>سامي</h3>
                        <p>تقني الكترونيات</p>
                    </div>
                </div>
                <div class="card">
                    <img loading="lazy" src="{{ url_for('static', filename='images/2.png') }}" alt="team member image">
                    <div class="data">
                        <h3>علي</h3>
                        <p>مطور برمجيات</p>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section id="3">
        <div class="services">
            <h2>الخدمات</h2>
            <div class="content">
                <div class="card">
                    <img loading="lazy" src="{{ url_for('static', filename='images/1.png') }}" alt="service image">
                    <div class="data">
                        <h3>الخدمة 1</h3>
                        <p>الشركة نفسها هي شركة ناجحة جدا. كمهندس معماري، إنه لمن دواعي سروري أن أكون مسؤولاً عن واجبات المكتب.</p>
                    </div>
                </div>
                <div class="card">
                    <img loading="lazy" src="{{ url_for('static', filename='images/1.png') }}" alt="service image">
                    <div class="data">
                        <h3>الخدمة 2</h3>
                        <p>الشركة نفسها هي شركة ناجحة جدا. كمهندس معماري، إنه لمن دواعي سروري أن أكون مسؤولاً عن واجبات المكتب.</p>
                    </div>
                </div>
                <div class="card">
                    <img loading="lazy" src="{{ url_for('static', filename='images/1.png') }}" alt="service image">
                    <div class="data">
                        <h3>الخدمة 3</h3>
                        <p>الشركة نفسها هي شركة ناجحة جدا. كمهندس معماري، إنه لمن دواعي سروري أن أكون مسؤولاً عن واجبات المكتب.</p>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section id="4">
        <div class="partners">
            <h2>الشركاء</h2>
            <div class="content">
                <div class="card">
                    <img loading="lazy" src="{{ url_for('static', filename='images/2.png') }}" alt="partner image">
                    <div class="data">
                        <h3>البلدية</h3>
                    </div>
                </div>
                <div class="card">
                    <img loading="lazy" src="{{ url_for('static', filename='images/2.png') }}" alt="partner image">
                    <div class="data">
                        <h3>دار الذكاء الاصطناعي</h3>
                    </div>
                </div>
                <div class="card">
                    <img loading="lazy" src="{{ url_for('static', filename='images/2.png') }}" alt="partner image">
                    <div class="data">
                        <h3>جامعة الوادي</h3>
                    </div>
                </div>
            </div>
        </div>
    </section>

    {% if not current_user.is_authenticated %}
    <section id="5">
        <div class="join">
            <div class="content">
                <p>سارع وكن جزءًا من مجتمعنا</p>
                <a href="{{ url_for('users.login' ) }}">انضمام</a>
            </div>
        </div>
    </section>
    {% endif %}

    <section>
        <div class="content">
            <div class="map">
                <iframe loading="lazy" src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d918.5924195128173!2d6.858102682037836!3d33.39523922304687!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sar!2sdz!4v1708380536979!5m2!1sar!2sdz" style="border:0;" allowfullscreen="" referrerpolicy="no-referrer-when-downgrade"></iframe>
            </div>
            <div class="contact">
                <p>رقم الهاتف</p><span>0666 555 333</span>
                <p>البريد الالكتروني</p><span>miknassa@gmail.com</span>
                <p>العنوان</p><span>الجزائر الوادي - جامعة الوادي</span>
            </div>
        </div>
    </section>

</main>
<footer>
    <div class="copyright">
        <span>&nbsp;Copyright©2024</span>
    </div>
</footer>
{% endblock body %}

miknassa/templates/pages/map.html
{% extends 'layoutWithBootstrap.html' %}

{% block stylesheets %}
<link rel="stylesheet" href="https://unpkg.com/leaflet/dist/leaflet.css" />
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
<link rel="stylesheet" href="{{ url_for('static', filename='css/app.css' ) }}">
{% endblock stylesheets %}

{% block body %}
{% include 'additions/flashMessages.html' %}
<script src="https://unpkg.com/leaflet/dist/leaflet.js"></script>


<div id="map"></div>
<div class="markerInfo">
    <h1>شاحنة النفايات</h1>
    <div class="contentInfo">

        <div class="info">
            <p>اسم السائق</p><span>محمد محمد</span>
        </div>
        <div class="info">
            <p>رقم الشاحنة</p><span>112</span>
        </div>
        <div class="info">
            <p>نوع الشاحنة</p><span>شاحنة ضاغطة</span>
        </div>
        <div class="info">
            <p>بلدية</p><span>الوادي</span>
        </div>
        <div class="info">
            <p>خط السّير رقم</p><span>03</span>
        </div>
        <div class="info">
            <p>معلومات اضافيّة</p><span>لا يوجد</span>
        </div>

    </div>
</div>

<script src="{{ url_for('static', filename='js/app.js') }}"></script>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
{% endblock body %}

miknassa/templates/pages/operation.html
<div id="operation" class="container">
  <h1>قائمة التنبيهات</h1>
  <div class="alerts">
    <div class="alert-item">
      <div class="location">الموقع الأول</div>
      <div class="status status-green"></div>
    </div>
    <div class="alert-item">
      <div class="location">الموقع الثاني</div>
      <div class="status status-red"></div>
    </div>
    <div class="alert-item">
      <div class="location">الموقع الأول</div>
      <div class="status status-green"></div>
    </div>
    <div class="alert-item">
      <div class="location">الموقع الثاني</div>
      <div class="status status-red"></div>
    </div>
    <div class="alert-item">
      <div class="location">الموقع الأول</div>
      <div class="status status-green"></div>
    </div>
    <div class="alert-item">
      <div class="location">الموقع الثاني</div>
      <div class="status status-red"></div>
    </div>
    <div class="alert-item">
      <div class="location">الموقع الأول</div>
      <div class="status status-green"></div>
    </div>
    <div class="alert-item">
      <div class="location">الموقع الثاني</div>
      <div class="status status-red"></div>
    </div>
    <div class="alert-item">
      <div class="location">الموقع الأول</div>
      <div class="status status-green"></div>
    </div>
    <div class="alert-item">
      <div class="location">الموقع الثاني</div>
      <div class="status status-red"></div>
    </div>
    <div class="alert-item">
      <div class="location">الموقع الأول</div>
      <div class="status status-green"></div>
    </div>
    <div class="alert-item">
      <div class="location">الموقع الثاني</div>
      <div class="status status-red"></div>
    </div>
    <div class="alert-item">
      <div class="location">الموقع الأول</div>
      <div class="status status-green"></div>
    </div>
    <div class="alert-item">
      <div class="location">الموقع الثاني</div>
      <div class="status status-red"></div>
    </div>
    <div class="alert-item">
      <div class="location">الموقع الأول</div>
      <div class="status status-green"></div>
    </div>
    <div class="alert-item">
      <div class="location">الموقع الاخير</div>
      <div class="status status-red"></div>
    </div>
    <!-- إكمال العناصر الأخرى حسب الحاجة -->
  </div>
</div>

miknassa/templates/pages/profile.html
{% extends 'layoutWithBootstrap.html' %}

{% block body %}
{% include 'parts/nav.html' %}
{% include 'additions/flashMessages.html' %}

<div class="container loginContainer">
    <div class="forms">
        <div class="formBox">
            <div class="row g-3">

                <div class="col-12 field">
                    <img src="{{ image }}" alt="صورة الحساب" width="150px" height="150px">
                </div>

                <div class="col-sm-6 field">
                    <p class="form-label"> الاسم الأول</p>
                    <input class="form-control" type="" value="{{ userData.firstName }}" disabled readonly>
                </div>
                <div class="col-sm-6 field">
                    <p class="form-label"> الاسم الأخير</p>
                    <input class="form-control" type="" value="{{ userData.lastName }}" disabled readonly>
                </div>
                <div class="col-sm-8 field">
                    <p class="form-label"> اسم المستخدم</p>
                    <input class="form-control" type="" value="{{ userData.username }}" disabled readonly>
                </div>
                <div class="col-sm-4 field">
                    <p class="form-label"> الجنس</p>
                    {% if userData.gender == 'male' %}
                    <input class="form-control" type="" value="ذكـر" disabled readonly>
                    {% else %}
                    <input class="form-control" type="" value="انثـى" disabled readonly>
                    {% endif %}
                </div>
                <div class="col-12 field">
                    <p class="form-label"> البريد الإلكتروني</p>
                    <input class="form-control" type="" value="{{ userData.email }}" disabled readonly>
                </div>
                <div class="col-12 field">
                    <p class="form-label"> رقم الهاتف</p>
                    <input class="form-control" type="" value="{{ userData.phoneNumber }}" disabled readonly>
                </div>

                <div class="col-md-4 field">
                    <p class="form-label"> الولاية</p>
                    <input class="form-control" type="" value="{{ address.wilaya }}" disabled readonly>
                </div>

                <div class="col-md-4 field">
                    <p class="form-label"> الدائرة</p>
                    <input class="form-control" type="" value="{{ address.dayra }}" disabled readonly>
                </div>

                <div class="col-md-4 field">
                    <p class="form-label"> البلدية</p>
                    <input class="form-control" type="" value="{{ address.municipality }}" disabled readonly>
                </div>

                <div class="col-md-4 field">
                    <p class="form-label"> رقم الدار</p>
                    <input class="form-control" type="" value="{{ userData.houseNumber }}" disabled readonly>
                </div>

                <div class="col-md-8 field">
                    <p class="form-label"> العنوان الجغرافي</p>
                    <input class="form-control" type="" value="{{ userData.location }}" disabled readonly>
                </div>

                <div class="col-md-6 field">
                    <p class="form-label"> تاريخ الميلاد</p>
                    <input class="form-control" type="" value="{{ userData.birthDate }}" disabled readonly>
                </div>

                <div class="col-md-6 field">
                    <p class="form-label"> مكان الميلاد</p>
                    <input class="form-control" type="" value="{{ userData.birthPlace }}" disabled readonly>
                </div>

            </div>
            <a href="{{ url_for('users.editProfile' ) }}" class="btn btn-success mt-5">تعديل الحساب</a>
            </form>
        </div>
    </div>
</div>


{% endblock body %}

miknassa/templates/pages/roleChanging.html
<div id="roleChanging" class="container">
    <h1>قائمة أدوار المستخدمين</h1>
    <div class="items">
        <div class="item">
            <span class="item-icon">👤</span>
            <span class="username">مستخدم 1</span>
            <span class="role">مشرف</span>
        </div>
        <div class="item">
            <span class="item-icon">👤</span>
            <span class="username">مستخدم 2</span>
            <span class="role">مستخدم عادي</span>
        </div>
        <div class="item">
            <span class="item-icon">👤</span>
            <span class="username">مستخدم 3</span>
            <span class="role">مشرف</span>
        </div>
        <div class="item">
            <span class="item-icon">👤</span>
            <span class="username">مستخدم 4</span>
            <span class="role">مستخدم عادي</span>
        </div>
        <div class="item">
            <span class="item-icon">👤</span>
            <span class="username">مستخدم 5</span>
            <span class="role">مشرف</span>
        </div>
        <div class="item">
            <span class="item-icon">👤</span>
            <span class="username">مستخدم 4</span>
            <span class="role">مستخدم عادي</span>
        </div>
        <div class="item">
            <span class="item-icon">👤</span>
            <span class="username">مستخدم 5</span>
            <span class="role">مشرف</span>
        </div>
        <div class="item">
            <span class="item-icon">👤</span>
            <span class="username">مستخدم 4</span>
            <span class="role">مستخدم عادي</span>
        </div>
        <div class="item">
            <span class="item-icon">👤</span>
            <span class="username">مستخدم 5</span>
            <span class="role">مشرف</span>
        </div>
        <div class="item">
            <span class="item-icon">👤</span>
            <span class="username">مستخدم 4</span>
            <span class="role">مستخدم عادي</span>
        </div>
        <div class="item">
            <span class="item-icon">👤</span>
            <span class="username">مستخدم 5</span>
            <span class="role">مشرف</span>
        </div>
        <div class="item">
            <span class="item-icon">👤</span>
            <span class="username">مستخدم 4</span>
            <span class="role">مستخدم عادي</span>
        </div>
        <div class="item">
            <span class="item-icon">👤</span>
            <span class="username">مستخدم 5</span>
            <span class="role">مشرف</span>
        </div>
        <div class="item">
            <span class="item-icon">👤</span>
            <span class="username">مستخدم 4</span>
            <span class="role">مستخدم عادي</span>
        </div>
        <div class="item">
            <span class="item-icon">👤</span>
            <span class="username">مستخدم 5</span>
            <span class="role">مشرف</span>
        </div>
        <div class="item">
            <span class="item-icon">👤</span>
            <span class="username">مستخدم 4</span>
            <span class="role">مستخدم عادي</span>
        </div>
        <div class="item">
            <span class="item-icon">👤</span>
            <span class="username">مستخدم 5</span>
            <span class="role">مشرف</span>
        </div>
        <div class="item">
            <span class="item-icon">👤</span>
            <span class="username">مستخدم 4</span>
            <span class="role">مستخدم عادي</span>
        </div>
        <div class="item">
            <span class="item-icon">👤</span>
            <span class="username">مستخدم أخير</span>
            <span class="role">مشرف</span>
        </div>
    </div>
</div>

miknassa/templates/pages/truckAdding.html
<div id="truckAdding" class="container">
    <h1>أدرج شاحنة جديدة</h1>
    <form>
        <input type="text" class="input-field" id="matricule" placeholder="01254 012 39" name="matricule" required>
        <br>
        <select class="dropdown-field" id="username" name="username" required>
            <option value="" disabled selected>السائق</option>
            <option value="سائق 1">سائق 1</option>
            <option value="سائق 2">سائق 2</option>
            <option value="سائق 3">سائق 3</option>
        </select>
        <br>
        <select class="dropdown-field" id="typeName" name="typeName" required>
            <option value="" disabled selected>نوع الشاحنة</option>
            <option value="نوع 1">نوع 1</option>
            <option value="نوع 2">نوع 2</option>
            <option value="نوع 3">نوع 3</option>
        </select>
        <br>
        <button type="submit" class="button">إدراج</button>
    </form>
</div>