miknassa/main/routes.py
from flask import Blueprint, render_template
from flask_login import current_user

mainBp = Blueprint("main", __name__)


@mainBp.route("/")
def home():
    isHomepage = True
    if current_user.is_authenticated:
        username = current_user.username
        return render_template(
            "pages/home.html", username=username, isHomepage=isHomepage
        )

    return render_template("pages/home.html", isHomepage=isHomepage)

miknassa/users/routes.py
from flask import Blueprint
from flask import render_template, flash, redirect, url_for, request
from flask_login import login_user, current_user, logout_user, login_required
from miknassa.users.forms import (
    JoinForm,
    LoginForm,
    EditProfileForm,
    ChangePasswordForm,
    ForgotPasswordForm,
    ResetPasswordForm,
)
from miknassa.models import User, Municipality, Dayra, Wilaya
from miknassa.users.helper import sendResetEmail
from miknassa.helper import renameImage
from miknassa import db, bcrypt


usersBp = Blueprint("users", __name__)


@usersBp.route("/miknassa", methods=["GET", "POST"])
def login():
    isHomepage = False
    isLoginpage = True

    try:
        if current_user.is_authenticated:
            return redirect(url_for("main.home"))

        joinForm = JoinForm()
        loginForm = LoginForm()

        if request.form.get("submit") == "انضمام":
            if joinForm.validate_on_submit():
                hashedPassword = bcrypt.generate_password_hash(
                    joinForm.password.data
                ).decode("utf-8")
                user = User(
                    firstName=joinForm.firstName.data,
                    lastName=joinForm.lastName.data,
                    username=joinForm.username.data,
                    gender=joinForm.gender.data,
                    email=joinForm.email.data,
                    phoneNumber=joinForm.phoneNumber.data,
                    municipalityId=joinForm.municipality.data,
                    userTypeId=1,
                    password=hashedPassword,
                )
                db.session.add(user)
                db.session.commit()
                flash(
                    f"مرحبا بك {joinForm.username.data}، تم انشاء الحساب بنجاح.",
                    "success",
                )
                return redirect(url_for("users.login"))
            else:
                flash("تأكّد من صحة الإدخال.", "warning")
    except Exception as e:
        db.session.rollback()
        # raise
        flash("يوجد مشكلة فالإتّصال\nحاول مجدّدا في وقت لاحق", 500, "error")

    finally:
        db.session.close()

    try:
        if request.form.get("submit") == "دخـول":
            if loginForm.validate_on_submit():
                user = User.query.filter_by(email=loginForm.email.data).first()

                if user and bcrypt.check_password_hash(
                    user.password, loginForm.password.data
                ):
                    login_user(user, remember=loginForm.remember.data)
                    nextPage = request.args.get("next")
                    flash(f"مرحبا {user.username} تم تسجيل الدخول بنجاح.", "success")
                    if user.userTypeId == 1:
                        return (
                            redirect(nextPage)
                            if nextPage
                            else redirect(url_for("main.home"))
                        )
                    elif user.userTypeId == 2:
                        return (
                            redirect(nextPage)
                            if nextPage
                            else redirect(url_for("application.dashboard"))
                        )
                    elif user.userTypeId == 3:
                        return (
                            redirect(nextPage)
                            if nextPage
                            else redirect(url_for("application.dashboard"))
                        )
                    else:
                        flash("يوجد خلل في الحساب", "error")
                else:
                    flash("فشل تسجيل الدخول، حاول مجدّدًا.", "error")
    except Exception as e:
        # raise
        flash("يوجد مشكلة فالإتّصال\nحاول مجدّدا في وقت لاحق", 500, "error")

    finally:
        db.session.close()

    return render_template(
        "forms/login.html",
        joinForm=joinForm,
        loginForm=loginForm,
        isHomepage=isHomepage,
        isLoginpage = isLoginpage,
    )


@usersBp.route("/logout")
@login_required
def logout():
    logout_user()
    flash("تم تسجيل الخروج بنجاح", "success")
    return redirect(url_for("users.login"))


@usersBp.route("/reset password", methods=["GET", "POST"])
def forgotPassword():
    isHomepage = False

    try:
        if current_user.is_authenticated:
            return redirect(url_for("main.home"))
        forgotPasswordForm = ForgotPasswordForm()
        if forgotPasswordForm.validate_on_submit():
            user = User.query.filter_by(email=forgotPasswordForm.email.data).first()
            if user:
                sendResetEmail(user)
            flash(
                "إذا كان هذا الحساب موجود فعلا فستستقبل بريدا إلكترونيًّا لاستعادة كلمة المرور.",
                "info",
            )
            return redirect(url_for("users.login"))
    except Exception as e:
        db.session.close()
        # raise
        flash("يوجد مشكلة فالإتّصال\nحاول مجدّدا في وقت لاحق", 500, "error")

    return render_template(
        "forms/forgotPassword.html",
        title="Reset Password",
        forgotPasswordForm=forgotPasswordForm,
        isHomepage=isHomepage,
    )


@usersBp.route("/reset password/<token>", methods=["GET", "POST"])
def resetPassword(token):
    resetPasswordForm = ResetPasswordForm()
    isHomepage = False

    try:
        if current_user.is_authenticated:
            return redirect(url_for("main.home"))

        user = User.verifyResetToken(token)

        if not user:
            flash("الرمز الخاص غير متاح أو منتهي الصلاحية.", "warning")
            return redirect(url_for("users.forgotPassword"))

        if resetPasswordForm.validate_on_submit():
            hashedPassword = bcrypt.generate_password_hash(
                resetPasswordForm.password.data
            ).decode("utf-8")
            user.password = hashedPassword
            db.session.commit()
            flash("تم تحديث كلمة مرورك بنجاح، تستطيع الآن تسجيل الدخول.", "success")
            return redirect(url_for("users.login"))

    except Exception as e:
        db.session.rollback()
        db.session.close()
        # raise
        flash("يوجد مشكلة فالإتّصال\nحاول مجدّدا في وقت لاحق", 500, "error")

    return render_template(
        "forms/resetPassword.html",
        title="Reset Password",
        resetPasswordForm=resetPasswordForm,
        isHomepage=isHomepage,
    )


@usersBp.route("/profile")
@login_required
def profile():
    isHomepage = False
    isProfilepage = True

    try:
        userData = User.query.filter_by(id=current_user.id).first()
        municipality = Municipality.query.filter_by(id=userData.municipalityId).first()
        dayra = Dayra.query.filter_by(id=municipality.dayraId).first()
        wilaya = Wilaya.query.filter_by(id=dayra.wilayaId).first()
        address = {
            "wilaya": wilaya.name,
            "dayra": dayra.name,
            "municipality": municipality.name,
        }
        image = url_for("static", filename=f"media/{userData.imageFile}")
        return render_template(
            "pages/profile.html",
            userData=userData,
            address=address,
            image=image,
            isHomepage=isHomepage,
            isProfilepage=isProfilepage,
        )
    except Exception as e:
        # raise
        flash("يوجد مشكلة فالإتّصال\nحاول مجدّدا في وقت لاحق", 500, "error")
        return redirect(url_for("users.login"))

    finally:
        db.session.close()


@usersBp.route("/edit profile", methods=["GET", "POST"])
@login_required
def editProfile():
    isHomepage = False
    username = current_user.username

    try:
        user = User.query.filter_by(id=current_user.id).first()
        municipality = Municipality.query.filter_by(id=user.municipalityId).first()
        dayra = Dayra.query.filter_by(id=municipality.dayraId).first()
        wilaya = Wilaya.query.filter_by(id=dayra.wilayaId).first()
        address = {
            "wilaya": wilaya.name,
            "dayra": dayra.name,
            "municipality": municipality.name,
        }
        editProfileForm = EditProfileForm()
        image = url_for("static", filename=f"media/{current_user.imageFile}")

        if editProfileForm.validate_on_submit():
            if editProfileForm.imageFile.data:
                image = renameImage(editProfileForm.imageFile.data)
                user.imageFile = image

            user.firstName = (
                editProfileForm.firstName.data
                if editProfileForm.firstName.data
                else user.firstName
            )
            user.lastName = (
                editProfileForm.lastName.data
                if editProfileForm.lastName.data
                else user.lastName
            )
            user.username = (
                editProfileForm.username.data
                if editProfileForm.username.data
                else user.username
            )
            user.gender = (
                editProfileForm.gender.data
                if editProfileForm.gender.data
                else user.gender
            )
            user.email = (
                editProfileForm.email.data if editProfileForm.email.data else user.email
            )
            user.phoneNumber = (
                editProfileForm.phoneNumber.data
                if editProfileForm.phoneNumber.data
                else user.phoneNumber
            )
            user.municipalityId = (
                editProfileForm.municipality.data
                if editProfileForm.municipality.data
                else user.municipality
            )
            user.houseNumber = editProfileForm.houseNumber.data
            user.location = editProfileForm.location.data
            user.birthDate = (
                editProfileForm.birthDate.data
                if editProfileForm.birthDate.data
                else user.birthDate
            )
            user.birthPlace = editProfileForm.birthPlace.data

            db.session.commit()

miknassa/templates/parts/header.html
<header>
    {% include 'parts/nav.html' %}
    {% include 'additions/flashMessages.html' %}
    <div class="video">
        <video autoplay loop muted id="video-background">
            <source src="{{ url_for('static', filename='videos/4.mp4') }}" type="video/mp4" id="videoSrc">
            Your browser does not support the video tag.
        </video>
    </div>
    <div class="motto">
        <div class="headerText">
            <h1>نظام مكنسة لمدينة راقية</h1>
            <p>نظام متابعة حركة ومواعيد اخراج القمامة من أجل الحفاظ على شوارع نظيفة وخالية من أكوام القمامة المبعثرة</p>
        </div>
        <div class="content">
            <a href="" download="miknassa.apk" class="apkBtn">حمّله الآن</a>
            <!--<img src="{{ url_for('static', filename='images/3.webp') }}" alt="">-->
        </div>
    </div>
</header>

miknassa/templates/parts/nav.html
<nav>
    <div class="content">
        <div class="logo">مِـكنـسة</div>
        <div class="menuDiv">
            <div id="menuIcon" onclick="toggleMenu()">
                <svg style="margin-top: 10px;" xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="30" height="30"
                    viewBox="0 0 50 50">
                    <path
                        d="M 0 7.5 L 0 12.5 L 50 12.5 L 50 7.5 L 0 7.5 z M 0 22.5 L 0 27.5 L 50 27.5 L 50 22.5 L 0 22.5 z M 0 37.5 L 0 42.5 L 50 42.5 L 50 37.5 L 0 37.5 z">
                    </path>
                </svg>
            </div>
            <div id="menu">
                <div class="list">
                    {% if isHomepage %}
                    <a href="#1">مكنسة</a>
                    <a href="#2">الفريق</a>
                    <a href="#3">الخدمات</a>
                    <a href="#4">الشركاء</a>
                    {% endif %}

                    {% if current_user.is_authenticated %}
                    {% if isHomepage %}
                    {% if current_user.userTypeId != 1 %}
                    <a href="{{ url_for('application.dashboard') }}" id="navJoin">لوحة التحكم</a>
                    {% endif %}
                    {% else %}
                    <a href="{{ url_for('main.home') }}" id="navJoin">الرئيسيّة</a>
                    {% endif %}
                    {% if not isProfilepage %}
                    <a href="{{ url_for('users.profile') }}">{{ username }}</a>
                    {% endif %}
                    <a href="{{ url_for('users.logout') }}" id="logout">خروج</a>
                    {% else %}
                    {% if isHomepage %}
                    <a href="#5" id="navJoin">انضمام</a>
                    {% else %}
                    <a href="{{ url_for('main.home') }}">الرئيسيّة</a>
                    {% if not isLoginpage %}
                    <a href="{{ url_for('users.login') }}" id="navJoin">انضمام</a>
                    {% endif %}
                    {% endif %}
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</nav>


<script src="{{ url_for('static', filename='js/navMenu.js') }}"></script>